 
 
#ifndef ENGINE_SHARED_PROTOCOL7_H
#define ENGINE_SHARED_PROTOCOL7_H

#include <base/types.h>

namespace protocol7
{
	enum
	{
		NETMSG_NULL = 0,

		 
		 
		NETMSG_INFO,

		 
		NETMSG_MAP_CHANGE,  
		NETMSG_MAP_DATA,  
		NETMSG_SERVERINFO,
		NETMSG_CON_READY,  
		NETMSG_SNAP,  
		NETMSG_SNAPEMPTY,  
		NETMSG_SNAPSINGLE,  
		NETMSG_SNAPSMALL,  
		NETMSG_INPUTTIMING,  
		NETMSG_RCON_AUTH_ON,  
		NETMSG_RCON_AUTH_OFF,  
		NETMSG_RCON_LINE,  
		NETMSG_RCON_CMD_ADD,
		NETMSG_RCON_CMD_REM,

		NETMSG_UNUSED1,
		NETMSG_UNUSED2,

		 
		NETMSG_READY,  
		NETMSG_ENTERGAME,
		NETMSG_INPUT,  
		NETMSG_RCON_CMD,  
		NETMSG_RCON_AUTH,  
		NETMSG_REQUEST_MAP_DATA,  

		NETMSG_UNUSED3,
		NETMSG_UNUSED4,

		 
		NETMSG_PING,
		NETMSG_PING_REPLY,
		NETMSG_UNUSED5,

		NETMSG_MAPLIST_ENTRY_ADD,  
		NETMSG_MAPLIST_ENTRY_REM,
	};

	enum
	{
		NET_CTRLMSG_KEEPALIVE = 0,
		NET_CTRLMSG_CONNECT,
		NET_CTRLMSG_ACCEPT,
		NET_CTRLMSG_UNUSED,
		NET_CTRLMSG_CLOSE,
		NET_CTRLMSG_TOKEN,
	};

	enum
	{
		MAX_NAME_LENGTH = 16,
		MAX_NAME_ARRAY_SIZE = MAX_NAME_LENGTH * UTF8_BYTE_LENGTH + 1,
		MAX_CLAN_LENGTH = 12,
		MAX_CLAN_ARRAY_SIZE = MAX_CLAN_LENGTH * UTF8_BYTE_LENGTH + 1,
		MAX_SKIN_LENGTH = 24,
		MAX_SKIN_ARRAY_SIZE = MAX_SKIN_LENGTH * UTF8_BYTE_LENGTH + 1,
	};

	namespace FinishTime
	{
		inline constexpr int NOT_FINISHED = -1;
	}
}

#endif
