 
 
#ifndef ENGINE_SHARED_PROTOCOL_H
#define ENGINE_SHARED_PROTOCOL_H

#include <engine/shared/protocol7.h>

#include <bitset>

 

enum
{
	NETMSG_EX = 0,

	 
	 
	NETMSG_INFO,

	 
	NETMSG_MAP_CHANGE,  
	NETMSG_MAP_DATA,  
	NETMSG_CON_READY,  
	NETMSG_SNAP,  
	NETMSG_SNAPEMPTY,  
	NETMSG_SNAPSINGLE,  
	NETMSG_SNAPSMALL,  
	NETMSG_INPUTTIMING,  
	NETMSG_RCON_AUTH_STATUS,  
	NETMSG_RCON_LINE,  

	NETMSG_UNUSED1,
	NETMSG_UNUSED2,

	 
	NETMSG_READY,  
	NETMSG_ENTERGAME,
	NETMSG_INPUT,  
	NETMSG_RCON_CMD,  
	NETMSG_RCON_AUTH,  
	NETMSG_REQUEST_MAP_DATA,  

	NETMSG_UNUSED3,
	NETMSG_UNUSED4,

	 
	NETMSG_PING,
	NETMSG_PING_REPLY,
	NETMSG_UNUSED5,

	 
	NETMSG_RCON_CMD_ADD,
	NETMSG_RCON_CMD_REM,

	NUM_NETMSGS,
};

 
enum
{
	SERVER_TICK_SPEED = 50,
	SERVER_FLAG_PASSWORD = 1 << 0,
	SERVER_FLAG_TIMESCORE = 1 << 1,
	SERVERINFO_LEVEL_MIN = 0,
	SERVERINFO_LEVEL_MAX = 2,

	MAX_SERVER_ADDRESSES = 16,
	SERVERINFO_MAX_CLIENTS = 128,
	MAX_CLIENTS = 128,
	VANILLA_MAX_CLIENTS = 16,
	SERVER_MAX_CLIENTS = 64,
	MAX_CHECKPOINTS = 25,
	MIN_TICK = 0,
	MAX_TICK = 0x6FFFFFFF,

	MAX_INPUT_SIZE = 128,
	MAX_SNAPSHOT_PACKSIZE = 900,

	MAX_NAME_LENGTH = 16,
	MAX_CLAN_LENGTH = 12,
	MAX_SKIN_LENGTH = 24,

	 
	 
	MSGFLAG_VITAL = 1 << 0,
	 
	MSGFLAG_FLUSH = 1 << 1,
	 
	MSGFLAG_NORECORD = 1 << 2,
	 
	MSGFLAG_RECORD = 1 << 3,
	 
	MSGFLAG_NOSEND = 1 << 4,
};

enum
{
	VERSION_NONE = -1,
	VERSION_VANILLA = 0,
	VERSION_DDRACE = 1,
	VERSION_DDNET_OLD = 2,
	VERSION_DDNET_WHISPER = 217,
	VERSION_DDNET_ANTIPING_PROJECTILE = 604,
	VERSION_DDNET_UPDATER_FIXED = 707,
	VERSION_DDNET_GAMETICK = 10042,
	VERSION_DDNET_EARLY_VERSION = 13020,
	VERSION_DDNET_MSG_LEGACY = 15040,
	VERSION_DDNET_INDEPENDENT_SPECTATORS_TEAM = 16000,
	VERSION_DDNET_WEAPON_SHIELDS = 16010,
	VERSION_DDNET_NEW_HUD = 16020,
	VERSION_DDNET_MULTI_LASER = 16040,
	VERSION_DDNET_ENTITY_NETOBJS = 16200,
	VERSION_DDNET_REDIRECT = 17020,
	VERSION_DDNET_PLAYERFLAG_SPEC_CAM = 18090,
	VERSION_DDNET_RECONNECT = 18090,
	VERSION_DDNET_128_PLAYERS = 19000,
	VERSION_DDNET_PREINPUT = 19040,
	VERSION_DDNET_SAVE_CODE = 19060,
	VERSION_DDNET_IMPORTANT_ALERT = 19060,
	VERSION_DDNET_MAP_BESTTIME = 19070,
};

namespace TuneZone
{
	inline constexpr int OVERRIDE_NONE = -1;
	inline constexpr int NUM = 256;
};

namespace FinishTime
{
	inline constexpr int NOT_FINISHED_TIMESCORE = -9999;
	inline constexpr int NOT_FINISHED_MILLIS = -1;
	inline constexpr int UNSET = -2;
}

typedef std::bitset<MAX_CLIENTS> CClientMask;

#endif
